/**
 * Curated asset groups for the Explore Assets section.
 * Each group has a default symbol list and optional year-specific overrides.
 * Symbols include short display names to avoid extra API calls.
 */

export type AssetGroupCategory =
  | "sector"
  | "theme"
  | "asset-class"
  | "event"
  | "market";

export type SectorFilter =
  | "All"
  | "Technology"
  | "Healthcare"
  | "Energy"
  | "Financials"
  | "Consumer"
  | "Industrials"
  | "Materials"
  | "Utilities"
  | "Real Estate"
  | "Communications"
  | "Precious Metals"
  | "Crypto"
  | "Biotech";

export type MarketFilter = "All" | "US" | "International" | "Crypto";

export interface SymbolEntry {
  symbol: string;
  name: string;
}

export interface AssetGroup {
  id: string;
  /** Title shown in the card. Use [year] placeholder. */
  title: string;
  /** Short description. Use [year] placeholder. */
  description: string;
  category: AssetGroupCategory;
  sector: SectorFilter;
  market: MarketFilter;
  /** Default symbol list, used when no year-specific override exists. */
  defaultSymbols: SymbolEntry[];
  /** Year-specific symbol overrides keyed by 4-digit year. */
  yearSymbols?: Record<number, SymbolEntry[]>;
  /** Metric used to sort assets within the card. */
  sortBy: "yearReturn" | "volume";
  /** Controls bento grid width. */
  layout: "wide" | "normal";
  /** Icon name (lucide) */
  icon: string;
}

// ---------------------------------------------------------------------------
// Group definitions
// ---------------------------------------------------------------------------

export const ASSET_GROUPS: AssetGroup[] = [
  // ── EVENT GROUPS ──────────────────────────────────────────────────────────
  {
    id: "sp500-top-performers",
    title: "S&P 500 Top Performers of [year]",
    description: "Best performing S&P 500 components for [year]",
    category: "event",
    sector: "All",
    market: "US",
    sortBy: "yearReturn",
    layout: "wide",
    icon: "TrendingUp",
    defaultSymbols: [
      { symbol: "NVDA", name: "NVIDIA" },
      { symbol: "META", name: "Meta" },
      { symbol: "AVGO", name: "Broadcom" },
      { symbol: "MSFT", name: "Microsoft" },
      { symbol: "AAPL", name: "Apple" },
      { symbol: "AMZN", name: "Amazon" },
      { symbol: "LLY", name: "Eli Lilly" },
      { symbol: "VST", name: "Vistra" },
      { symbol: "CEG", name: "Constellation Energy" },
      { symbol: "GE", name: "GE Aerospace" },
    ],
    yearSymbols: {
      2020: [
        { symbol: "TSLA", name: "Tesla" },
        { symbol: "ENPH", name: "Enphase Energy" },
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "ETSY", name: "Etsy" },
        { symbol: "GNRC", name: "Generac Holdings" },
        { symbol: "SEDG", name: "SolarEdge" },
        { symbol: "RUN", name: "Sunrun" },
        { symbol: "PENN", name: "Penn Gaming" },
        { symbol: "DXCM", name: "DexCom" },
        { symbol: "POOL", name: "Pool Corp" },
      ],
      2021: [
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "FCX", name: "Freeport-McMoRan" },
        { symbol: "DVN", name: "Devon Energy" },
        { symbol: "MOS", name: "Mosaic" },
        { symbol: "CF", name: "CF Industries" },
        { symbol: "HES", name: "Hess Corp" },
        { symbol: "BRK-B", name: "Berkshire Hathaway" },
        { symbol: "MRNA", name: "Moderna" },
        { symbol: "MSFT", name: "Microsoft" },
        { symbol: "GOOGL", name: "Alphabet" },
      ],
      2022: [
        { symbol: "XOM", name: "ExxonMobil" },
        { symbol: "CVX", name: "Chevron" },
        { symbol: "OXY", name: "Occidental" },
        { symbol: "CF", name: "CF Industries" },
        { symbol: "MOS", name: "Mosaic" },
        { symbol: "DVN", name: "Devon Energy" },
        { symbol: "COP", name: "ConocoPhillips" },
        { symbol: "HES", name: "Hess Corp" },
        { symbol: "VLO", name: "Valero Energy" },
        { symbol: "PSX", name: "Phillips 66" },
      ],
      2023: [
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "META", name: "Meta" },
        { symbol: "RCL", name: "Royal Caribbean" },
        { symbol: "CCL", name: "Carnival" },
        { symbol: "NCLH", name: "Norwegian Cruise" },
        { symbol: "PHM", name: "PulteGroup" },
        { symbol: "LEN", name: "Lennar" },
        { symbol: "UBER", name: "Uber" },
        { symbol: "TSLA", name: "Tesla" },
        { symbol: "MGM", name: "MGM Resorts" },
      ],
      2024: [
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "PLTR", name: "Palantir" },
        { symbol: "AXON", name: "Axon Enterprise" },
        { symbol: "VST", name: "Vistra Energy" },
        { symbol: "CEG", name: "Constellation Energy" },
        { symbol: "IRM", name: "Iron Mountain" },
        { symbol: "NRG", name: "NRG Energy" },
        { symbol: "RCL", name: "Royal Caribbean" },
        { symbol: "UAL", name: "United Airlines" },
        { symbol: "GEV", name: "GE Vernova" },
      ],
      2025: [
        { symbol: "PLTR", name: "Palantir" },
        { symbol: "AVGO", name: "Broadcom" },
        { symbol: "AAPL", name: "Apple" },
        { symbol: "LLY", name: "Eli Lilly" },
        { symbol: "GS", name: "Goldman Sachs" },
        { symbol: "JPM", name: "JPMorgan" },
        { symbol: "META", name: "Meta" },
        { symbol: "MSFT", name: "Microsoft" },
        { symbol: "GOOGL", name: "Alphabet" },
        { symbol: "AMZN", name: "Amazon" },
      ],
      2026: [
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "META", name: "Meta" },
        { symbol: "AVGO", name: "Broadcom" },
        { symbol: "MSFT", name: "Microsoft" },
        { symbol: "AAPL", name: "Apple" },
        { symbol: "AMZN", name: "Amazon" },
        { symbol: "LLY", name: "Eli Lilly" },
        { symbol: "VST", name: "Vistra" },
        { symbol: "CEG", name: "Constellation Energy" },
        { symbol: "GE", name: "GE Aerospace" },
      ],
    },
  },
  {
    id: "sp500-worst-performers",
    title: "S&P 500 Biggest Losers of [year]",
    description: "Worst performing S&P 500 components for [year]",
    category: "event",
    sector: "All",
    market: "US",
    sortBy: "yearReturn",
    layout: "wide",
    icon: "TrendingDown",
    defaultSymbols: [
      { symbol: "INTC", name: "Intel" },
      { symbol: "NFLX", name: "Netflix" },
      { symbol: "PARA", name: "Paramount" },
      { symbol: "WBA", name: "Walgreens" },
      { symbol: "MRNA", name: "Moderna" },
      { symbol: "PFE", name: "Pfizer" },
      { symbol: "SBUX", name: "Starbucks" },
      { symbol: "DG", name: "Dollar General" },
      { symbol: "APA", name: "APA Corp" },
      { symbol: "DLTR", name: "Dollar Tree" },
    ],
    yearSymbols: {
      2020: [
        { symbol: "CCL", name: "Carnival" },
        { symbol: "UAL", name: "United Airlines" },
        { symbol: "AAL", name: "American Airlines" },
        { symbol: "DAL", name: "Delta Air Lines" },
        { symbol: "MGM", name: "MGM Resorts" },
        { symbol: "MRO", name: "Marathon Oil" },
        { symbol: "OXY", name: "Occidental" },
        { symbol: "HAL", name: "Halliburton" },
        { symbol: "SLB", name: "Schlumberger" },
        { symbol: "F", name: "Ford" },
      ],
      2022: [
        { symbol: "META", name: "Meta" },
        { symbol: "COIN", name: "Coinbase" },
        { symbol: "RIVN", name: "Rivian" },
        { symbol: "NFLX", name: "Netflix" },
        { symbol: "SNAP", name: "Snap" },
        { symbol: "ROKU", name: "Roku" },
        { symbol: "TWTR", name: "Twitter" },
        { symbol: "PYPL", name: "PayPal" },
        { symbol: "ABNB", name: "Airbnb" },
        { symbol: "RBLX", name: "Roblox" },
      ],
      2023: [
        { symbol: "ENPH", name: "Enphase Energy" },
        { symbol: "SEDG", name: "SolarEdge" },
        { symbol: "PFE", name: "Pfizer" },
        { symbol: "MRNA", name: "Moderna" },
        { symbol: "PARA", name: "Paramount" },
        { symbol: "CVS", name: "CVS Health" },
        { symbol: "BIIB", name: "Biogen" },
        { symbol: "WBD", name: "Warner Bros Discovery" },
        { symbol: "SVB", name: "SVB Financial" },
        { symbol: "FRC", name: "First Republic Bank" },
      ],
      2024: [
        { symbol: "INTC", name: "Intel" },
        { symbol: "PARA", name: "Paramount" },
        { symbol: "MRNA", name: "Moderna" },
        { symbol: "WBA", name: "Walgreens" },
        { symbol: "DG", name: "Dollar General" },
        { symbol: "DLTR", name: "Dollar Tree" },
        { symbol: "PFE", name: "Pfizer" },
        { symbol: "SBUX", name: "Starbucks" },
        { symbol: "ALGN", name: "Align Technology" },
        { symbol: "APA", name: "APA Corp" },
      ],
    },
  },
  {
    id: "biggest-ipos",
    title: "Biggest IPOs of [year]",
    description: "Top IPOs and newly listed companies from [year]",
    category: "event",
    sector: "All",
    market: "US",
    sortBy: "yearReturn",
    layout: "wide",
    icon: "Rocket",
    defaultSymbols: [
      { symbol: "RDDT", name: "Reddit" },
      { symbol: "ALAB", name: "Astera Labs" },
      { symbol: "KVYO", name: "Klaviyo" },
      { symbol: "ARM", name: "Arm Holdings" },
      { symbol: "CART", name: "Instacart" },
    ],
    yearSymbols: {
      2020: [
        { symbol: "ABNB", name: "Airbnb" },
        { symbol: "DASH", name: "DoorDash" },
        { symbol: "SNOW", name: "Snowflake" },
        { symbol: "PLTR", name: "Palantir" },
        { symbol: "U", name: "Unity Software" },
        { symbol: "ASAN", name: "Asana" },
        { symbol: "WISH", name: "ContextLogic" },
        { symbol: "POSH", name: "Poshmark" },
      ],
      2021: [
        { symbol: "COIN", name: "Coinbase" },
        { symbol: "RBLX", name: "Roblox" },
        { symbol: "RIVN", name: "Rivian" },
        { symbol: "DUOL", name: "Duolingo" },
        { symbol: "TOST", name: "Toast" },
        { symbol: "DKNG", name: "DraftKings" },
        { symbol: "APP", name: "AppLovin" },
        { symbol: "LCID", name: "Lucid Group" },
      ],
      2022: [
        { symbol: "MBLY", name: "Mobileye" },
        { symbol: "CABA", name: "Cabaletta Bio" },
        { symbol: "TPVG", name: "TriplePoint Venture" },
        { symbol: "DTM", name: "DT Midstream" },
      ],
      2023: [
        { symbol: "ARM", name: "Arm Holdings" },
        { symbol: "CART", name: "Instacart (Maplebear)" },
        { symbol: "KVYO", name: "Klaviyo" },
        { symbol: "BIRK", name: "Birkenstock" },
        { symbol: "KRTX", name: "Karuna Therapeutics" },
      ],
      2024: [
        { symbol: "RDDT", name: "Reddit" },
        { symbol: "ALAB", name: "Astera Labs" },
        { symbol: "LINE", name: "Lineage" },
        { symbol: "LNZA", name: "LanzaTech" },
        { symbol: "VERA", name: "Vera Therapeutics" },
      ],
      2025: [
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "PLTR", name: "Palantir" },
        { symbol: "MSFT", name: "Microsoft" },
        { symbol: "AAPL", name: "Apple" },
        { symbol: "META", name: "Meta" },
      ],
      2026: [
        { symbol: "RDDT", name: "Reddit" },
        { symbol: "ALAB", name: "Astera Labs" },
        { symbol: "ARM", name: "Arm Holdings" },
        { symbol: "CART", name: "Instacart" },
        { symbol: "KVYO", name: "Klaviyo" },
      ],
    },
  },
  {
    id: "top-volume-movers",
    title: "Top Volume Movers in [year]",
    description: "Most actively traded US equities by average daily volume in [year]",
    category: "event",
    sector: "All",
    market: "US",
    sortBy: "volume",
    layout: "wide",
    icon: "BarChart2",
    defaultSymbols: [
      { symbol: "SPY", name: "SPDR S&P 500 ETF" },
      { symbol: "QQQ", name: "Invesco QQQ" },
      { symbol: "AAPL", name: "Apple" },
      { symbol: "TSLA", name: "Tesla" },
      { symbol: "NVDA", name: "NVIDIA" },
      { symbol: "AMZN", name: "Amazon" },
      { symbol: "AMD", name: "AMD" },
      { symbol: "META", name: "Meta" },
      { symbol: "MSFT", name: "Microsoft" },
      { symbol: "BAC", name: "Bank of America" },
    ],
  },
  {
    id: "retail-favorites",
    title: "Retail Investor Favorites of [year]",
    description: "Most popular stocks among retail investors in [year]",
    category: "theme",
    sector: "All",
    market: "US",
    sortBy: "yearReturn",
    layout: "wide",
    icon: "Users",
    defaultSymbols: [
      { symbol: "NVDA", name: "NVIDIA" },
      { symbol: "TSLA", name: "Tesla" },
      { symbol: "AAPL", name: "Apple" },
      { symbol: "PLTR", name: "Palantir" },
      { symbol: "MSTR", name: "MicroStrategy" },
      { symbol: "COIN", name: "Coinbase" },
      { symbol: "GME", name: "GameStop" },
      { symbol: "AMC", name: "AMC Entertainment" },
    ],
    yearSymbols: {
      2020: [
        { symbol: "TSLA", name: "Tesla" },
        { symbol: "AAPL", name: "Apple" },
        { symbol: "AMZN", name: "Amazon" },
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "ZM", name: "Zoom" },
        { symbol: "ABNB", name: "Airbnb" },
        { symbol: "PLTR", name: "Palantir" },
        { symbol: "NIO", name: "NIO Inc." },
      ],
      2021: [
        { symbol: "GME", name: "GameStop" },
        { symbol: "AMC", name: "AMC Entertainment" },
        { symbol: "BB", name: "BlackBerry" },
        { symbol: "NOK", name: "Nokia" },
        { symbol: "CLOV", name: "Clover Health" },
        { symbol: "SPCE", name: "Virgin Galactic" },
        { symbol: "COIN", name: "Coinbase" },
        { symbol: "RIVN", name: "Rivian" },
      ],
      2022: [
        { symbol: "GME", name: "GameStop" },
        { symbol: "AMC", name: "AMC Entertainment" },
        { symbol: "LCID", name: "Lucid Group" },
        { symbol: "RIVN", name: "Rivian" },
        { symbol: "BBBY", name: "Bed Bath & Beyond" },
        { symbol: "SOFI", name: "SoFi Technologies" },
        { symbol: "HOOD", name: "Robinhood" },
        { symbol: "PLTR", name: "Palantir" },
      ],
      2023: [
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "AI", name: "C3.ai" },
        { symbol: "PLTR", name: "Palantir" },
        { symbol: "GME", name: "GameStop" },
        { symbol: "META", name: "Meta" },
        { symbol: "TSLA", name: "Tesla" },
        { symbol: "ARM", name: "Arm Holdings" },
        { symbol: "BBAI", name: "BigBear.ai" },
      ],
      2024: [
        { symbol: "NVDA", name: "NVIDIA" },
        { symbol: "MSTR", name: "MicroStrategy" },
        { symbol: "COIN", name: "Coinbase" },
        { symbol: "GME", name: "GameStop" },
        { symbol: "TSLA", name: "Tesla" },
        { symbol: "PLTR", name: "Palantir" },
        { symbol: "RDDT", name: "Reddit" },
        { symbol: "SMCI", name: "Super Micro Computer" },
      ],
    },
  },

  // ── ASSET CLASS GROUPS ───────────────────────────────────────────────────
  {
    id: "precious-metals",
    title: "Precious Metals in [year]",
    description: "Gold, silver, and platinum group metals performance for [year]",
    category: "asset-class",
    sector: "Precious Metals",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Gem",
    defaultSymbols: [
      { symbol: "GLD", name: "SPDR Gold Shares" },
      { symbol: "SLV", name: "iShares Silver Trust" },
      { symbol: "PPLT", name: "Aberdeen Platinum ETF" },
      { symbol: "PALL", name: "abrdn Palladium ETF" },
      { symbol: "GDX", name: "VanEck Gold Miners" },
      { symbol: "NEM", name: "Newmont" },
      { symbol: "GOLD", name: "Barrick Gold" },
      { symbol: "WPM", name: "Wheaton Precious Metals" },
    ],
  },
  {
    id: "crypto-assets",
    title: "Crypto Assets in [year]",
    description: "Leading cryptocurrencies tracked by Yahoo Finance for [year]",
    category: "asset-class",
    sector: "Crypto",
    market: "Crypto",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Bitcoin",
    defaultSymbols: [
      { symbol: "BTC-USD", name: "Bitcoin" },
      { symbol: "ETH-USD", name: "Ethereum" },
      { symbol: "BNB-USD", name: "BNB" },
      { symbol: "SOL-USD", name: "Solana" },
      { symbol: "XRP-USD", name: "XRP" },
      { symbol: "ADA-USD", name: "Cardano" },
      { symbol: "DOGE-USD", name: "Dogecoin" },
      { symbol: "AVAX-USD", name: "Avalanche" },
    ],
  },
  {
    id: "bond-etfs",
    title: "Fixed Income Performance in [year]",
    description: "Bond ETF performance across durations and credit quality for [year]",
    category: "asset-class",
    sector: "All",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Landmark",
    defaultSymbols: [
      { symbol: "AGG", name: "iShares Core US Agg Bond" },
      { symbol: "BND", name: "Vanguard Total Bond Market" },
      { symbol: "TLT", name: "iShares 20+ Yr Treasury" },
      { symbol: "IEF", name: "iShares 7-10 Yr Treasury" },
      { symbol: "SHY", name: "iShares 1-3 Yr Treasury" },
      { symbol: "HYG", name: "iShares High Yield Corp Bond" },
      { symbol: "LQD", name: "iShares Investment Grade Corp" },
      { symbol: "TIP", name: "iShares TIPS Bond ETF" },
    ],
  },
  {
    id: "international-markets",
    title: "International Markets in [year]",
    description: "Global equity ETFs tracking international markets for [year]",
    category: "market",
    sector: "All",
    market: "International",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Globe",
    defaultSymbols: [
      { symbol: "EFA", name: "iShares MSCI EAFE" },
      { symbol: "EEM", name: "iShares MSCI Emerging Mkts" },
      { symbol: "VEU", name: "Vanguard FTSE All-World ex-US" },
      { symbol: "EWJ", name: "iShares MSCI Japan" },
      { symbol: "EWG", name: "iShares MSCI Germany" },
      { symbol: "EWU", name: "iShares MSCI UK" },
      { symbol: "FXI", name: "iShares China Large-Cap" },
      { symbol: "EWA", name: "iShares MSCI Australia" },
      { symbol: "EWC", name: "iShares MSCI Canada" },
      { symbol: "EWZ", name: "iShares MSCI Brazil" },
    ],
  },

  // ── SECTOR GROUPS ─────────────────────────────────────────────────────────
  {
    id: "tech-leaders",
    title: "Technology Leaders in [year]",
    description: "Leading technology companies and the XLK sector ETF for [year]",
    category: "sector",
    sector: "Technology",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Cpu",
    defaultSymbols: [
      { symbol: "XLK", name: "Technology Select SPDR" },
      { symbol: "AAPL", name: "Apple" },
      { symbol: "MSFT", name: "Microsoft" },
      { symbol: "NVDA", name: "NVIDIA" },
      { symbol: "GOOGL", name: "Alphabet" },
      { symbol: "META", name: "Meta" },
      { symbol: "AVGO", name: "Broadcom" },
      { symbol: "AMD", name: "AMD" },
      { symbol: "INTC", name: "Intel" },
      { symbol: "ORCL", name: "Oracle" },
    ],
  },
  {
    id: "healthcare-leaders",
    title: "Healthcare Leaders in [year]",
    description: "Top healthcare and pharmaceutical companies for [year]",
    category: "sector",
    sector: "Healthcare",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Stethoscope",
    defaultSymbols: [
      { symbol: "XLV", name: "Health Care Select SPDR" },
      { symbol: "JNJ", name: "Johnson & Johnson" },
      { symbol: "UNH", name: "UnitedHealth Group" },
      { symbol: "LLY", name: "Eli Lilly" },
      { symbol: "ABBV", name: "AbbVie" },
      { symbol: "MRK", name: "Merck" },
      { symbol: "TMO", name: "Thermo Fisher" },
      { symbol: "ABT", name: "Abbott Labs" },
      { symbol: "PFE", name: "Pfizer" },
      { symbol: "BMY", name: "Bristol-Myers Squibb" },
    ],
  },
  {
    id: "energy-leaders",
    title: "Energy Leaders in [year]",
    description: "Oil, gas, and energy sector performance for [year]",
    category: "sector",
    sector: "Energy",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Flame",
    defaultSymbols: [
      { symbol: "XLE", name: "Energy Select SPDR" },
      { symbol: "XOM", name: "ExxonMobil" },
      { symbol: "CVX", name: "Chevron" },
      { symbol: "COP", name: "ConocoPhillips" },
      { symbol: "SLB", name: "SLB" },
      { symbol: "EOG", name: "EOG Resources" },
      { symbol: "MPC", name: "Marathon Petroleum" },
      { symbol: "OXY", name: "Occidental" },
      { symbol: "PSX", name: "Phillips 66" },
      { symbol: "DVN", name: "Devon Energy" },
    ],
  },
  {
    id: "financials-leaders",
    title: "Financial Leaders in [year]",
    description: "Banks, insurers, and financial services companies for [year]",
    category: "sector",
    sector: "Financials",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "DollarSign",
    defaultSymbols: [
      { symbol: "XLF", name: "Financial Select SPDR" },
      { symbol: "JPM", name: "JPMorgan Chase" },
      { symbol: "BAC", name: "Bank of America" },
      { symbol: "WFC", name: "Wells Fargo" },
      { symbol: "GS", name: "Goldman Sachs" },
      { symbol: "MS", name: "Morgan Stanley" },
      { symbol: "C", name: "Citigroup" },
      { symbol: "BLK", name: "BlackRock" },
      { symbol: "AXP", name: "American Express" },
      { symbol: "V", name: "Visa" },
    ],
  },
  {
    id: "consumer-discretionary",
    title: "Consumer Discretionary in [year]",
    description: "Retail, leisure, and discretionary spending stocks for [year]",
    category: "sector",
    sector: "Consumer",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "ShoppingBag",
    defaultSymbols: [
      { symbol: "XLY", name: "Consumer Discret. Select SPDR" },
      { symbol: "AMZN", name: "Amazon" },
      { symbol: "TSLA", name: "Tesla" },
      { symbol: "HD", name: "Home Depot" },
      { symbol: "MCD", name: "McDonald's" },
      { symbol: "NKE", name: "Nike" },
      { symbol: "LOW", name: "Lowe's" },
      { symbol: "SBUX", name: "Starbucks" },
      { symbol: "TGT", name: "Target" },
      { symbol: "BKNG", name: "Booking Holdings" },
    ],
  },
  {
    id: "consumer-staples",
    title: "Consumer Staples in [year]",
    description: "Essential goods and staples companies for [year]",
    category: "sector",
    sector: "Consumer",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "ShoppingCart",
    defaultSymbols: [
      { symbol: "XLP", name: "Consumer Staples Select SPDR" },
      { symbol: "PG", name: "Procter & Gamble" },
      { symbol: "KO", name: "Coca-Cola" },
      { symbol: "PEP", name: "PepsiCo" },
      { symbol: "WMT", name: "Walmart" },
      { symbol: "COST", name: "Costco" },
      { symbol: "CL", name: "Colgate-Palmolive" },
      { symbol: "MO", name: "Altria Group" },
      { symbol: "PM", name: "Philip Morris" },
      { symbol: "KHC", name: "Kraft Heinz" },
    ],
  },
  {
    id: "industrials-leaders",
    title: "Industrial Leaders in [year]",
    description: "Manufacturing, aerospace, and industrial sector for [year]",
    category: "sector",
    sector: "Industrials",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Factory",
    defaultSymbols: [
      { symbol: "XLI", name: "Industrial Select SPDR" },
      { symbol: "BA", name: "Boeing" },
      { symbol: "HON", name: "Honeywell" },
      { symbol: "UNP", name: "Union Pacific" },
      { symbol: "UPS", name: "UPS" },
      { symbol: "CAT", name: "Caterpillar" },
      { symbol: "DE", name: "Deere & Company" },
      { symbol: "LMT", name: "Lockheed Martin" },
      { symbol: "RTX", name: "RTX Corp" },
      { symbol: "GE", name: "GE Aerospace" },
    ],
  },
  {
    id: "materials-leaders",
    title: "Materials Leaders in [year]",
    description: "Chemicals, mining, and materials sector stocks for [year]",
    category: "sector",
    sector: "Materials",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Layers",
    defaultSymbols: [
      { symbol: "XLB", name: "Materials Select SPDR" },
      { symbol: "LIN", name: "Linde" },
      { symbol: "APD", name: "Air Products" },
      { symbol: "ECL", name: "Ecolab" },
      { symbol: "SHW", name: "Sherwin-Williams" },
      { symbol: "NEM", name: "Newmont" },
      { symbol: "FCX", name: "Freeport-McMoRan" },
      { symbol: "NUE", name: "Nucor" },
      { symbol: "DOW", name: "Dow Inc." },
      { symbol: "PPG", name: "PPG Industries" },
    ],
  },
  {
    id: "utilities-leaders",
    title: "Utilities in [year]",
    description: "Electric, gas, and water utility companies for [year]",
    category: "sector",
    sector: "Utilities",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Zap",
    defaultSymbols: [
      { symbol: "XLU", name: "Utilities Select SPDR" },
      { symbol: "NEE", name: "NextEra Energy" },
      { symbol: "DUK", name: "Duke Energy" },
      { symbol: "SO", name: "Southern Company" },
      { symbol: "D", name: "Dominion Energy" },
      { symbol: "AEP", name: "American Electric Power" },
      { symbol: "EXC", name: "Exelon" },
      { symbol: "XEL", name: "Xcel Energy" },
      { symbol: "SRE", name: "Sempra" },
      { symbol: "PEG", name: "PSEG" },
    ],
  },
  {
    id: "real-estate",
    title: "Real Estate (REITs) in [year]",
    description: "Real estate investment trusts across property sectors for [year]",
    category: "sector",
    sector: "Real Estate",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Building2",
    defaultSymbols: [
      { symbol: "XLRE", name: "Real Estate Select SPDR" },
      { symbol: "AMT", name: "American Tower" },
      { symbol: "PLD", name: "Prologis" },
      { symbol: "CCI", name: "Crown Castle" },
      { symbol: "EQIX", name: "Equinix" },
      { symbol: "PSA", name: "Public Storage" },
      { symbol: "DLR", name: "Digital Realty" },
      { symbol: "WELL", name: "Welltower" },
      { symbol: "O", name: "Realty Income" },
      { symbol: "SPG", name: "Simon Property Group" },
    ],
  },
  {
    id: "communication-services",
    title: "Communication Services in [year]",
    description: "Media, telecom, and internet platform companies for [year]",
    category: "sector",
    sector: "Communications",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Radio",
    defaultSymbols: [
      { symbol: "XLC", name: "Communication Svcs Select SPDR" },
      { symbol: "GOOGL", name: "Alphabet" },
      { symbol: "META", name: "Meta" },
      { symbol: "NFLX", name: "Netflix" },
      { symbol: "DIS", name: "Disney" },
      { symbol: "T", name: "AT&T" },
      { symbol: "VZ", name: "Verizon" },
      { symbol: "CMCSA", name: "Comcast" },
      { symbol: "TMUS", name: "T-Mobile" },
      { symbol: "SNAP", name: "Snap" },
    ],
  },
  {
    id: "biotech",
    title: "Biotech Leaders in [year]",
    description: "Biopharmaceutical and biotechnology companies for [year]",
    category: "sector",
    sector: "Biotech",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Microscope",
    defaultSymbols: [
      { symbol: "XBI", name: "SPDR S&P Biotech ETF" },
      { symbol: "BIIB", name: "Biogen" },
      { symbol: "AMGN", name: "Amgen" },
      { symbol: "GILD", name: "Gilead Sciences" },
      { symbol: "REGN", name: "Regeneron" },
      { symbol: "VRTX", name: "Vertex Pharmaceuticals" },
      { symbol: "ILMN", name: "Illumina" },
      { symbol: "MRNA", name: "Moderna" },
      { symbol: "BNTX", name: "BioNTech" },
      { symbol: "NVAX", name: "Novavax" },
    ],
  },

  // ── THEME GROUPS ──────────────────────────────────────────────────────────
  {
    id: "mega-cap",
    title: "Mega Cap Companies in [year]",
    description: "Largest companies by market capitalization (the Magnificent 7 + others) in [year]",
    category: "theme",
    sector: "All",
    market: "US",
    sortBy: "yearReturn",
    layout: "wide",
    icon: "Crown",
    defaultSymbols: [
      { symbol: "NVDA", name: "NVIDIA" },
      { symbol: "AAPL", name: "Apple" },
      { symbol: "MSFT", name: "Microsoft" },
      { symbol: "GOOGL", name: "Alphabet" },
      { symbol: "AMZN", name: "Amazon" },
      { symbol: "META", name: "Meta" },
      { symbol: "TSLA", name: "Tesla" },
      { symbol: "BRK-B", name: "Berkshire Hathaway" },
      { symbol: "LLY", name: "Eli Lilly" },
      { symbol: "AVGO", name: "Broadcom" },
    ],
  },
  {
    id: "high-dividend",
    title: "High Dividend Payers in [year]",
    description: "Top dividend-yielding stocks and income ETFs for [year]",
    category: "theme",
    sector: "All",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Percent",
    defaultSymbols: [
      { symbol: "VYM", name: "Vanguard High Dividend Yield" },
      { symbol: "DVY", name: "iShares Select Dividend" },
      { symbol: "SCHD", name: "Schwab US Dividend Equity" },
      { symbol: "T", name: "AT&T" },
      { symbol: "VZ", name: "Verizon" },
      { symbol: "MO", name: "Altria Group" },
      { symbol: "PM", name: "Philip Morris" },
      { symbol: "O", name: "Realty Income" },
      { symbol: "KO", name: "Coca-Cola" },
      { symbol: "JNJ", name: "Johnson & Johnson" },
    ],
  },
  {
    id: "small-cap",
    title: "Small Cap Performers in [year]",
    description: "Small and mid-cap equity performance via key ETFs for [year]",
    category: "theme",
    sector: "All",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "TrendingUp",
    defaultSymbols: [
      { symbol: "IWM", name: "iShares Russell 2000" },
      { symbol: "IJR", name: "iShares Core S&P Small-Cap" },
      { symbol: "VB", name: "Vanguard Small-Cap" },
      { symbol: "MDY", name: "SPDR Mid Cap 400" },
      { symbol: "VO", name: "Vanguard Mid-Cap" },
      { symbol: "IJH", name: "iShares Core S&P Mid-Cap" },
      { symbol: "SCHA", name: "Schwab Small-Cap" },
      { symbol: "VXF", name: "Vanguard Extended Market" },
    ],
  },
  {
    id: "clean-energy",
    title: "Clean Energy in [year]",
    description: "Solar, wind, and clean energy transition stocks for [year]",
    category: "theme",
    sector: "Energy",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Wind",
    defaultSymbols: [
      { symbol: "ICLN", name: "iShares Global Clean Energy" },
      { symbol: "ENPH", name: "Enphase Energy" },
      { symbol: "SEDG", name: "SolarEdge Technologies" },
      { symbol: "RUN", name: "Sunrun" },
      { symbol: "FSLR", name: "First Solar" },
      { symbol: "NEE", name: "NextEra Energy" },
      { symbol: "PLUG", name: "Plug Power" },
      { symbol: "BLNK", name: "Blink Charging" },
      { symbol: "CHPT", name: "ChargePoint" },
      { symbol: "BE", name: "Bloom Energy" },
    ],
  },
  {
    id: "ai-enablers",
    title: "AI & Data Center Enablers in [year]",
    description: "Semiconductors, cloud, and infrastructure powering AI in [year]",
    category: "theme",
    sector: "Technology",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "Brain",
    defaultSymbols: [
      { symbol: "NVDA", name: "NVIDIA" },
      { symbol: "AMD", name: "AMD" },
      { symbol: "AVGO", name: "Broadcom" },
      { symbol: "MSFT", name: "Microsoft (Azure)" },
      { symbol: "AMZN", name: "Amazon (AWS)" },
      { symbol: "GOOGL", name: "Alphabet (GCP)" },
      { symbol: "ORCL", name: "Oracle" },
      { symbol: "DELL", name: "Dell Technologies" },
      { symbol: "SMCI", name: "Super Micro Computer" },
      { symbol: "PLTR", name: "Palantir" },
    ],
  },
  {
    id: "top-mutual-funds",
    title: "Top Performing Mutual Funds in [year]",
    description: "Leading US mutual funds by year-to-date return in [year]",
    category: "theme",
    sector: "All",
    market: "US",
    sortBy: "yearReturn",
    layout: "normal",
    icon: "PieChart",
    defaultSymbols: [
      { symbol: "VFIAX", name: "Vanguard 500 Index Adm" },
      { symbol: "FXAIX", name: "Fidelity 500 Index" },
      { symbol: "VTSAX", name: "Vanguard Total Stock Mkt Adm" },
      { symbol: "VWUSX", name: "Vanguard Growth Index" },
      { symbol: "FCNTX", name: "Fidelity Contrafund" },
      { symbol: "AGTHX", name: "Amer. Funds Growth Fund" },
      { symbol: "PRGFX", name: "T. Rowe Price Growth Stock" },
      { symbol: "VIMAX", name: "Vanguard Mid-Cap Index Adm" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Filter helpers
// ---------------------------------------------------------------------------

export const AVAILABLE_YEARS = [2020, 2021, 2022, 2023, 2024, 2025, 2026];

export const SECTOR_FILTERS: SectorFilter[] = [
  "All",
  "Technology",
  "Healthcare",
  "Energy",
  "Financials",
  "Consumer",
  "Industrials",
  "Materials",
  "Utilities",
  "Real Estate",
  "Communications",
  "Precious Metals",
  "Crypto",
  "Biotech",
];

export const MARKET_FILTERS: MarketFilter[] = [
  "All",
  "US",
  "International",
  "Crypto",
];

/**
 * Returns the symbols to use for a given group in a given year.
 */
export function getGroupSymbols(group: AssetGroup, year: number): SymbolEntry[] {
  return group.yearSymbols?.[year] ?? group.defaultSymbols;
}

/**
 * Filter groups by sector and market.
 */
export function filterGroups(
  groups: AssetGroup[],
  sector: SectorFilter,
  market: MarketFilter
): AssetGroup[] {
  return groups.filter((g) => {
    const sectorMatch = sector === "All" || g.sector === sector || g.sector === "All";
    const marketMatch = market === "All" || g.market === market;
    return sectorMatch && marketMatch;
  });
}
